[package]
name = "concept-extractor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

async-openai = {version = "0.17"}
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
strum = "0.25"
strum_macros = "0.25"
thiserror = "1.0"
tokio = { version = "1.35", features=["full"]}
rocket = "0.5.0"


[lib]
name = "openai_api"
path = "src/openai_api.rs"

[[bin]]
name = "compile"
path = "src/compile.rs"

[[bin]]
name = "rest"
path = "src/rest-api.rs"